export class ProjectAlreadyInitializedError extends Error {
  constructor(projectPath: string) {
    super(`Project already initialized at ${projectPath}`);
    this.name = 'ProjectAlreadyInitializedError';
  }
}

export enum ErrorCode {
  // Core errors (Phase 1A spec)
  MANIFEST_INVALID = 'MANIFEST_INVALID',
  COMMAND_NOT_FOUND = 'COMMAND_NOT_FOUND',
  MCP_SPAWN_FAILED = 'MCP_SPAWN_FAILED',
  MCP_TIMEOUT = 'MCP_TIMEOUT',
  MCP_DISCONNECTED = 'MCP_DISCONNECTED',
  REGISTRY_UNREACHABLE = 'REGISTRY_UNREACHABLE',
  EXTENSION_NOT_FOUND = 'EXTENSION_NOT_FOUND',
  HOOK_FAILED = 'HOOK_FAILED',
  VAULT_DECRYPT_FAILED = 'VAULT_DECRYPT_FAILED',
  CONFIG_INVALID = 'CONFIG_INVALID',

  // Extension system errors (Phase 1B)
  MANIFEST_NOT_FOUND = 'MANIFEST_NOT_FOUND',
  COMMAND_HANDLER_NOT_FOUND = 'COMMAND_HANDLER_NOT_FOUND',
  COMMAND_EXECUTION_FAILED = 'COMMAND_EXECUTION_FAILED',
  MCP_CONNECTION_FAILED = 'MCP_CONNECTION_FAILED',
  MCP_REQUEST_FAILED = 'MCP_REQUEST_FAILED',
  MCP_PROCESS_CRASHED = 'MCP_PROCESS_CRASHED',
  INTERPOLATION_FAILED = 'INTERPOLATION_FAILED',
  JSON_RPC_PARSE_ERROR = 'JSON_RPC_PARSE_ERROR',
  JSON_RPC_INVALID_RESPONSE = 'JSON_RPC_INVALID_RESPONSE',
  ENGINE_INCOMPATIBLE = 'ENGINE_INCOMPATIBLE',
}
